---
title: Misc stuff
author: Jun
output: html_document
---
```{r include = FALSE}
# import libraries
library(DT)
library(dplyr)
library(vroom)
library(stringr)
```

## Notes:

## Steps:

## Todo:

## Info:



## EDA
spit out formatted names for DQMWG

input: 1 vectors, present, strings. 
fn: already has ordered factors as source of truth. Any not in vector is not
    present. Sort
output: return 2 vectors(in lists?), ordered, present, not present
```{r}

ordered <- c("Michael Thompson"
, "Miranda Li"
, "Alein Chun"
, "Paul Bouganim"
, "Joanne Chiu"
, "Marco Cifuentes"
, "Donell Cohen"
, "Donald Davies"
, "Tod Davis"
, "Rachel Fridman"
, "Jessica Hermosura"
, "Ha Hoang"
, "Jessica Hopkins"
, "Andrew Hudson"
, "Jennifer Kegle"
, "Mandy Law-Huang"
, "Walter Liem"
, "Susan Mangeno"
, "Julian Martinez"
, "Lilly Martirosyan"
, "Shad Nicks"
, "Soshi Odawara"
, "Ted Rafdal"
, "Dexter Reinoso"
, "Marcus Harrison"
, "Ron Ruckle"
, "Rachel Selmont"
, "Colleen Stalvey"
, "Susan Tiffany"
, "Eduardo Genao"
, "Hudson Stuck"
, "Erin Joyce"
, "Van Vu"
, "Michelle Fang"
, "Denise Abcede"
, "Jun Hernandez"
)

# can't have typos
# TODO: have typos outputted 
present <- c("Miranda Li", "Eduardo Genao", "Susan Tiffany", "Alein Chun",
             "Dexter Reinoso", "Donald Davies", "Erin Joyce", "Hudson Stuck",
             "Julian Martinez", "Jun Hernandez", "Mandy Law-Huang", 
             "Marco Cifuentes", "Marcus Harrison", "Michelle Fang", 
             "Michael Thompson", "Donell Cohen", "Rachel Fridman", "Soshi Odawara",
             "Ted Rafdal", "Van Vu", "Denise Abcede")

sorted <- (present[order(match(present, ordered))]) 
absent <- setdiff(ordered, sorted)
out <- c(paste(sorted, collapse = ", "), paste(absent, collapse = ", "))



# TODO: test ordered arg ctor
sort_names <- function(present, ordered = c()) {
    # proper order
    ordered <- c("Michael Thompson", "Miranda Li", "Alein Chun", "Paul Bouganim", 
                 "Joanne Chiu", "Marco Cifuentes", "Donell Cohen", "Donald Davies", 
                 "Tod Davis", "Rachel Fridman", "Jessica Hermosura", "Ha Hoang", 
                 "Jessica Hopkins", "Andrew Hudson", "Jennifer Kegle", "Mandy Law-Huang",
                 "Walter Liem", "Susan Mangeno", "Julian Martinez", "Lilly Martirosyan",
                 "Shad Nicks", "Soshi Odawara", "Ted Rafdal", "Dexter Reinoso",
                 "Marcus Harrison", "Ron Ruckle", "Rachel Selmont", "Colleen Stalvey", 
                 "Susan Tiffany", "Hudson Stuck", "Erin Joyce", "Van Vu", "Michelle Fang", 
                 "Jun Hernandez", "Janette Zetina", "Angelene Estiandan"
    )
    sorted <- (present[order(match(present, ordered))]) 
    absent <- setdiff(ordered, sorted)

    out <- c(paste(sorted, collapse = ", "), paste(absent, collapse = ", "))
    out

# TODO: add unrecognized names to another vector
# TODO: Add chair, co-chair titles
}

# unit test
got <- sort_names(present)

# write want, got





```




testing out image recognition with tesseract

```{r}

library(tesseract)
eng <- tesseract("eng")
text <- tesseract::ocr("http://jeroen.github.io/images/testocr.png", engine = eng)
cat(text)

eng <- tesseract("eng")
att1<- tesseract::ocr("images/att1_062122.PNG", engine = eng)
att2<- tesseract::ocr("images/att2_062122.PNG", engine = eng)
cat(att1)
cat(att2)

length(att1)
att1

# put in fn
test <- str_replace_all(att1, "[\\n]", ",")
test <- unlist(strsplit(test, ","))
ignore_vals <- c("", "Host", " me", "Cohost")
clean <- setdiff(test, ignore_vals)

#sort_names(clean)




image_rec <- function(img_path) {
    eng <- tesseract::tesseract("eng")
    names <- c()

    # change to map
    for (img in img_path) {
        att <- tesseract::ocr(img, engine = eng)
        names <- c(names, att)
    } 

    names <- paste(names,collapse = ",")
    names <- str_replace_all(names, "[\\n]", ",")
    names <- unlist(strsplit(names, ","))

    ignore_vals <- c("", "Host", " me", "Cohost")
    clean <- setdiff(names, ignore_vals)
    
}




# fix
path <- c("images/att1_062122.PNG", "images/att2_062122.PNG")

got <- image_rec(path)
sort_names(got)


```
omg this actually works 



```
# fn to convert names to 
# using R way, make df to map names, then join

# import csv table 
# combine into names fn?
```














